version: "3.7"
services:
  mysql:
    build: ./database
    container_name: DBmysql
    restart: always
    ports:
      - 5000:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "db_calculadora"
    volumes:
      - ./database/schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    links:
      - mysql
  frontend:
    container_name: calculadora
    restart: always
    build: ./calculadora
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge