version: "3.7"
services:
  mysql:
    build: ./database
    container_name: DBmysql
    restart: always
    ports:
      - 5000:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "db_calculadora"
    volumes:
      - ./database/schemas:/var/lib/mysql:rw
    networks:
      - Calcu
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./logs:/logs
    networks:
      - Calcu
  frontend:
    container_name: calculadora
    restart: always
    build: ./calculadora
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
    networks:
      - Calcu
volumes:
  schemas: {}
  logs: {}
networks:
  Calcu:
    driver: bridge